## TravisCI config:
# Created on 4 Aug 2014
#
language: python
python:
  - "3.4"
before_install:
    - sudo apt-get install python3-setuptools
    - pip install setuptools pip -U
    - pip install coveralls

install:
    - python setup.py build
    - python setup.py develop

# command to run tests
script:
    - python setup.py nosetests                     # Run Test-cases and Coverage.
    - python setup.py build_sphinx                  # Build html-docs.
    - python setup.py build_sphinx -b doctest       # Check code embeded in comments with `doctest`.
    - python setup.py sdist  --formats=zip,bztar    # Create archives for PyPI repo.

after_success:
    coveralls

branches:
  only:
    - master
