language: python
python:
  - "3.3"
  - "3.4"
# command to install dependencies
install: "pip install ."
# command to run tests
script:
    - nosetests
    - "cd docs && make html"

branches:
  only:
    - master
