language: python
python:
  - "3.4"
before_install: 
    - "sudo apt-get install python3-setuptools"
install: "pip install ."
# command to run tests
script:
    - "python setup.py test"
    - "python setup.py build_sphinx"
    - "cd docs && make doctest"

branches:
  only:
    - master
