## TravisCI config
#
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  # - "3.8-dev"  # too slow!
matrix:
  allow_failures:
    - python: 3.5
    #- python: "3.8-dev"

install:
    - python --version
    - pip install -e .[test]
    - pip list

script:
    - |
        if [[ "$TRAVIS_PYTHON_VERSION" = '3.7' ]]; then
            echo "+++ Checking all TCs, DTs & Coverage....";
            python setup.py test_all
        else
            echo "+++ Checking only TCs....";
            python setup.py test_code
        fi

    - |
        echo "+++ Checking README for PyPy...."
        ./bin/check_readme.sh

    - |
        echo "+++ Checking site...."
        pip install -e .[doc]
        python setup.py build_sphinx

    -   echo "+++ Checking install...."
        python setup.py install
        python setup.py build

    - |
        echo "+++  Checking archives for PyPI repo..."
        python setup.py sdist bdist_wheel

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then coveralls; fi
