## TravisCI config:
#   Created on 4 Aug 2014
#
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
before_install:
    - sudo apt-get install python3-setuptools
    - pip install setuptools pip -U
    - pip install coveralls
    - pip install sphinx

install:
    - python setup.py build_py
    - python setup.py develop

# command to run tests
script:
#    - python setup.py test_all                      # Nose tests, doctests in *.rst and modules, and report coverage.
    - python setup.py test_code                      # Nose tests, doctests in *.rst and modules, and report coverage.
    - python setup.py build_sphinx                  # Build html-docs.
    - python setup.py --long-description | rst2html.py  --halt=warning            # Ensure README valid ReST for PyPI.
    - python setup.py install
    - python setup.py sdist                         # Create archives for PyPI repo.

after_success:
    coveralls

branches:
  only:
    - master
