## TravisCI config
#
git:
    depth: 3
language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
# matrix:
#   allow_failures:
#     - python: "3.8-dev"
addons:
  apt:
    packages:
      - graphviz

install:
    - pip install pytest -U
    - pip install -e .[test]
    # pip fails to install `pydot `from graphtik's extras (report to https://github.com/pypa/pip#988)
    - pip install graphtik[sphinx]
    - pip list
    ## Re-create `*.ipynb` files from the paired `*.py` "py:percent" files.
    - ./Notebooks/recreate_ipynbs.sh

script:
    - ./Notebooks/recreate_pyalgo_h5.sh

    - |
        if [[ "$TRAVIS_PYTHON_VERSION" = '3.7' ]]; then
            echo "+++ Checking all TCs, DTs & Coverage....";
            pytest \
                --doctest-glob=README.rst \
                --doctest-modules \
                --cov=wltp.experiment \
                --cov=wltp.datamodel \
                --cov=wltp.engine \
                --cov=wltp.vehicle \
                --cov=wltp.vmax \
                --cov=wltp.downscale \
                --cov=wltp.invariants \
                --cov=wltp.io \
                --cov=wltp.utils \
                --cov=wltp.cycles
        else
            echo "+++ Checking only TCs....";
            pytest
        fi

    - python setup.py install
    - python setup.py build
    - python setup.py sdist bdist_wheel

after_success:
    - pip install coveralls
    - coveralls
