## TravisCI config:
# Created on 4 Aug 2014
#
language: python
python:
  - "3.4"
before_install:
    - sudo apt-get install python3-setuptools
    - pip install setuptools pip -U
    - pip install coveralls

install:
    - python setup.py build_py
    - python setup.py develop

# command to run tests
script:
    - python setup.py covertest                     # Run Test-cases and Coverage.
    - python setup.py build_sphinx                  # Build html-docs.
    - python setup.py doctest                       # Check code embeded in comments with `doctest`.
                                                    # Always PASS due to: https://bitbucket.org/birkenfeld/sphinx/issue/508/sphinx-should-exit-with-non-zero-exit-code
    - python setup.py sdist  --formats=zip,bztar    # Create archives for PyPI repo.

after_success:
    coveralls

branches:
  only:
    - master
