language: python
python:
  - "3.4"
before_install:
    - "sudo apt-get install python3-setuptools"
    - "pip install coveralls"
install: "pip install ."

# command to run tests
script:
    - "python setup.py build"
    - "python setup.py nosetests"
    - "python setup.py build_sphinx"
    - "python setup.py build_sphinx -b doctest"
after_success:
    coveralls

branches:
  only:
    - master
