## TravisCI config:
#   Created on 4 Aug 2014
#
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
before_install:
    - sudo apt-get install python3-setuptools

install:
    - pip install -r dev_requirements.txt
    - pip install .

# command to run tests
script:
    - if [[ $TRAVIS_PYTHON_VERSION = '3.4' ]]; then python setup.py doctest_docs; fi
    - if [[ $TRAVIS_PYTHON_VERSION = '3.4' ]]; then python setup.py doctest_code; fi
    - |
        if [[ $TRAVIS_PYTHON_VERSION = '2.7' ]]; then python setup.py test_code; fi
        if [[ $TRAVIS_PYTHON_VERSION = '3.3' ]]; then python setup.py test_code; fi
        if [[ $TRAVIS_PYTHON_VERSION = '3.4' ]]; then python setup.py test_code_cover; fi
    - python setup.py build_sphinx                   ## Build html-docs.

    ## Ensure README valid ReST for PyPI.
    ##  In case it fails, improve the filtering-code in ``setup.py``.
    - python setup.py --long-description | rst2html.py  --halt=warning > /dev/null

    - python setup.py sdist                         ## Create archives for PyPI repo.

after_success:
    coveralls

branches:
  only:
    - master

