language: python
python:
  - "3.4"
before_install:
    - "sudo apt-get install python3-setuptools"
install: "pip install ."
# command to run tests
script:
    - "python setup.py nosetests --with-coverage --cover-package wltp.model,wltp.experiment --cover-min-percentage=80"
    - "python setup.py build_sphinx"
    - "python setup.py build_sphinx -b doctest"
after_success:
    coveralls

branches:
  only:
    - master
